services:
  db:
    image: postgres:18.1-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - bingo

  idp:
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
    volumes:
      - .local_config/keycloak/config:/opt/keycloak/data/import
    networks:
      - bingo

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bingo-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - bingo

volumes:
  postgres_data:

networks:
  bingo:
