spring:
  application:
    name: Judgement Bingo
  datasource:
    url: "jdbc:postgresql://db:5432/bingo"
    username: bingo
    password: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

bingo:
  security:
    identity-providers:
      issuers:
        - issuer: http://localhost:8089/realms/local
          provider: KEYCLOAK
        - issuer: https://accounts.google.com
          provider: GOOGLE

logging:
  level:
    root: info
